"use client";

import React from 'react';

interface ShareCardProps {
    totalSongs: number;
    totalCountries: number;
    topCountries: Array<{ name: string; count: number }>;
}

export const ShareCard = React.forwardRef<HTMLDivElement, ShareCardProps>(({ totalSongs, totalCountries, topCountries }, ref) => {
    return (
        <div ref={ref} className="w-[600px] h-[400px] bg-nb-bg p-8 border-4 border-nb-text rounded-2xl flex flex-col justify-between relative overflow-hidden font-sans text-nb-text">
            {/* Background decoration */}
            <div className="absolute top-0 right-0 w-64 h-64 bg-nb-accent/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"></div>
            <div className="absolute bottom-0 left-0 w-64 h-64 bg-nb-accent/10 rounded-full blur-3xl translate-y-1/2 -translate-x-1/2"></div>

            {/* Header */}
            <div>
                <h1 className="text-4xl font-black uppercase tracking-tighter mb-1">Passporte Musical</h1>
                <p className="text-xl font-medium opacity-60 uppercase tracking-widest">SpotiMap Traveler</p>
            </div>

            {/* Stats Grid */}
            <div className="flex gap-8 my-6">
                <div className="bg-nb-bg-alt p-4 rounded-xl border-2 border-nb-border flex-1 text-center shadow-nb-sm">
                    <span className="block text-5xl font-black text-nb-accent mb-1">{totalCountries}</span>
                    <span className="text-xs font-bold uppercase tracking-wider opacity-70">Countries Visited</span>
                </div>
                <div className="bg-nb-bg-alt p-4 rounded-xl border-2 border-nb-border flex-1 text-center shadow-nb-sm">
                    <span className="block text-5xl font-black text-nb-accent mb-1">{totalSongs}</span>
                    <span className="text-xs font-bold uppercase tracking-wider opacity-70">Songs Collected</span>
                </div>
            </div>

            {/* Top Countries */}
            <div className="space-y-2">
                <p className="text-xs font-bold uppercase tracking-widest opacity-60 mb-2">Top Destinations</p>
                <div className="flex flex-wrap gap-2">
                    {topCountries.map((c, i) => (
                        <div key={c.name} className="flex items-center gap-2 bg-white/50 px-3 py-1.5 rounded-full border border-nb-text/10">
                            <span className="w-5 h-5 rounded-full bg-nb-accent text-white flex items-center justify-center text-[10px] font-bold">
                                {i + 1}
                            </span>
                            <span className="font-bold text-sm">{c.name}</span>
                        </div>
                    ))}
                </div>
            </div>

            {/* Footer */}
            <div className="flex justify-between items-end mt-4 pt-4 border-t-2 border-nb-text/10">
                <div className="text-xs font-mono opacity-50" suppressHydrationWarning>
                    ID: {typeof window !== 'undefined' ? Math.random().toString(36).substr(2, 9).toUpperCase() : 'GENERATING...'}
                </div>
                <div className="text-right">
                    <p className="text-xs font-bold uppercase opacity-50">Generated by</p>
                    <p className="text-lg font-black tracking-tight">SpotiMap 🌍</p>
                </div>
            </div>
        </div>
    );
});

ShareCard.displayName = 'ShareCard';
